# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 516)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.227, y1:0.261, x2:1, y2:1, stop:0.119318 rgba(129, 0, 137, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AccidentsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AccidentsBtn.setGeometry(QtCore.QRect(40, 170, 141, 71))
        self.AccidentsBtn.setStyleSheet("background-color: rgb(192, 192, 192);\n"
"border-radius: 10px;")
        self.AccidentsBtn.setObjectName("AccidentsBtn")
        self.DriversBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DriversBtn.setGeometry(QtCore.QRect(210, 170, 141, 71))
        self.DriversBtn.setStyleSheet("background-color: rgb(192, 192, 192);\n"
"border-radius: 10px;")
        self.DriversBtn.setObjectName("DriversBtn")
        self.FuelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FuelBtn.setGeometry(QtCore.QRect(380, 170, 141, 71))
        self.FuelBtn.setStyleSheet("background-color: rgb(192, 192, 192);\n"
"border-radius: 10px;")
        self.FuelBtn.setObjectName("FuelBtn")
        self.InspectionsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.InspectionsBtn.setGeometry(QtCore.QRect(550, 170, 141, 71))
        self.InspectionsBtn.setStyleSheet("background-color: rgb(192, 192, 192);\n"
"border-radius: 10px;")
        self.InspectionsBtn.setObjectName("InspectionsBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AccidentsBtn.setText(_translate("MainWindow", "Клиенты"))
        self.DriversBtn.setText(_translate("MainWindow", "Данные о вкладах"))
        self.FuelBtn.setText(_translate("MainWindow", "Сотрудники"))
        self.InspectionsBtn.setText(_translate("MainWindow", "Вклады"))
